budgeter/config/routes.rb
Rails.application.routes.draw do
  resources :trans
  resources :entries
  root 'entries#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

budgeter/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

budgeter/app/models/entry.rb
class Entry < ApplicationRecord
    has_many :transactions, dependent: :destroy
end

budgeter/app/models/test.rb
class Test < ApplicationRecord
end

budgeter/app/models/tran.rb
class Tran < ApplicationRecord
end

budgeter/app/models/transaction.rb
class Transaction < ApplicationRecord
belongs_to :entry
end

budgeter/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

budgeter/app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url, notice: 'Entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:title, :description)
    end
end

budgeter/app/controllers/trans_controller.rb
class TransController < ApplicationController
  before_action :set_tran, only: [:show, :edit, :update, :destroy]

  # GET /trans
  # GET /trans.json
  def index
    @trans = Tran.all
  end

  # GET /trans/1
  # GET /trans/1.json
  def show
  end

  # GET /trans/new
  def new
    @tran = Tran.new
  end

  # GET /trans/1/edit
  def edit
  end

  # POST /trans
  # POST /trans.json
  def create
    @tran = Tran.new(tran_params)

    respond_to do |format|
      if @tran.save
        format.html { redirect_to @tran, notice: 'Tran was successfully created.' }
        format.json { render :show, status: :created, location: @tran }
      else
        format.html { render :new }
        format.json { render json: @tran.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trans/1
  # PATCH/PUT /trans/1.json
  def update
    respond_to do |format|
      if @tran.update(tran_params)
        format.html { redirect_to @tran, notice: 'Tran was successfully updated.' }
        format.json { render :show, status: :ok, location: @tran }
      else
        format.html { render :edit }
        format.json { render json: @tran.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trans/1
  # DELETE /trans/1.json
  def destroy
    @tran.destroy
    respond_to do |format|
      format.html { redirect_to trans_url, notice: 'Tran was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tran
      @tran = Tran.find(params[:id])

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tran_params
      params.require(:tran).permit(:new)
    end
end

budgeter/app/helpers/application_helper.rb
module ApplicationHelper
end

budgeter/app/helpers/entries_helper.rb
module EntriesHelper
end

budgeter/app/helpers/trans_helper.rb
module TransHelper
end

budgeter/app/views/entries/_form.html.erb
<%= form_for(entry) do |f| %>
  <% if entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

budgeter/app/views/entries/edit.html.erb
<h1>Editing Entry</h1>

<%= render 'form', entry: @entry %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

budgeter/app/views/entries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Entries</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entries.each do |entry| %>
      <tr>
        <td><%= entry.title %></td>
        <td><%= entry.description %></td>
        <td><%= link_to 'Show', entry %></td>
        <td><%= link_to 'Edit', edit_entry_path(entry) %></td>
        <td><%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entry', new_entry_path %>

budgeter/app/views/entries/new.html.erb
<h1>New Entry</h1>

<%= render 'form', entry: @entry %>

<%= link_to 'Back', entries_path %>

budgeter/app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @entry.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @entry.description %>
</p>

<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>

budgeter/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budgeter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'default', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'default', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

budgeter/app/views/trans/_form.html.erb
<%= form_for(tran) do |f| %>
  <% if tran.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tran.errors.count, "error") %> prohibited this tran from being saved:</h2>

      <ul>
      <% tran.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :new %>
    <%= f.number_field :new %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
  <div>
    <%= f.label :trans_date %>
    <%= f.date_select :trans_date %>
  </div>
<% end %>

budgeter/app/views/trans/edit.html.erb
<h1>Editing Tran</h1>

<%= render 'form', tran: @tran %>

<%= link_to 'Show', @tran %> |
<%= link_to 'Back', trans_path %>

budgeter/app/views/trans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trans</h1>

<table>
  <thead>
    <tr>
      <th>New</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trans.each do |tran| %>
      <tr>
        <td><%= tran.new %></td>
        <td><%= link_to 'Show', tran %></td>
        <td><%= link_to 'Edit', edit_tran_path(tran) %></td>
        <td><%= link_to 'Destroy', tran, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tran', new_tran_path %>

budgeter/app/views/trans/new.html.erb
<h1>New Tran</h1>

<%= render 'form', tran: @tran %>

<%= link_to 'Back', trans_path %>

budgeter/app/views/trans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>New:</strong>
  <%= @tran.new %>
</p>

<%= link_to 'Edit', edit_tran_path(@tran) %> |
<%= link_to 'Back', trans_path %>